### ISSUE TITLE
Add sorting capability to stdout JSON file

### ISSUE THREAD

**Issue by ClydeDz** [tscanlin/processmd#27] opened 2020-10-15 09:09 UTC
Hi,

Fantastic library! I'm using your library to generate a single JSON file out of multiple markdown files. I'm using the following command to do so. 

`.\node_modules\.bin\processmd "inputFolder/**/*.{md}" --stdout --outputDir outputFolder > output.json`

Everything works fine, however, I noticed that the entries in the `fileMap` object of the output JSON are not sorted in the same order as the `sourceFileArray`. I'm wanting the contents in `fileMap` to be sorted somehow (either filename or date field?). I tried prefixing the markdown filenames with dates (201701, 201702...etc) and I also tried prefixing with alphabets (a-filename, b-filename...etc), however, neither sorts the results in `fileMap` in the right order.

Would be great to either get some direction on how should I go about sorting or if none available at the moment, then I'd really like to see a sort option become available in the near future. 

Thanks!

**Comment by tscanlin** [comment] 2020-10-18 19:00
Hey, good question!

This is actually something that I ran into as well and is the reason the sourceFileArray prop exists.
However, sorting object keys isn't something that is currently standard in JS. Last time I remember when I tested trying to sort object keys it worked in browsers (for legacy reasons), but I think I had issues with it in node.. however maybe this is worthy of another look.
See this for more into: https://stackoverflow.com/questions/1069666/sorting-object-property-by-values

**Comment by tscanlin** [comment] 2020-10-18 20:51
I made a PR for this, could you help test the change before I merge it?
https://github.com/tscanlin/processmd/pull/28/files

**Comment by ClydeDz** [comment] 2020-10-19 06:16
Tim,

Thanks for looking into this and working on a fix so promptly! I have downloaded the files from the fix branch and have tested locally. **Most** of the tests have passed except for one. I've added some details below. 

### Test summary:
✔️ Data in the `fileMap` object is sorted alphabetically.   
✔️ Filenames that are prefixed with date stamps (e.g. 20201910-filename) are sorted in ascending.     
✔️Files that were in subfolders of the YYYY pattern (e.g. 2020) are sorted first by YYYY in ascending order, then under each YYYY, they are sorted alphabetically.    
✔️ Files that were in generally named subfolders (e.g. books, audio, random) are sorted alphabetically first, then under each named folder, files are sorted alphabetically again.     
❌ When a folder has files and subfolders, the order in the `fileMap` object doesn't match with what's in `sourceFileArray`. The [advanced usage](https://github.com/tscanlin/processmd/tree/fix-sorting#advanced-usage) section in the README file of this project inspired this test. Please see a screenshot below to support this test. 

### Note:
ℹ️ In all of the above cases, I tried to match the `fileMap` order with what's in `sourceFileArray`.   
ℹ️ All the above tests were performed after running my existing script which basically runs something like:
`.\node_modules\.bin\processmd "inputFolder/**/*.{md}" --stdout --outputDir outputFolder > output.json`

### Supporting screenshots: 
![image](https://user-images.githubusercontent.com/13506613/96407665-61063080-123e-11eb-8489-d4eafbbf2115.png)
   
Hope this helps!

**Comment by tscanlin** [comment] 2020-10-23 07:05
Hey, sorry for the delay in responding, this week has been busy. But thank you so much for your excellent description of the issue, I found it to be extremely helpful! I've updated the PR with the code changes to correct this discrepancy.
https://github.com/tscanlin/processmd/pull/28/files

Let me know if you still have issue or if anything comes up in the future. Thanks again!

**Comment by ClydeDz** [comment] 2020-10-23 10:47
Hi Tim,

Not a problem at all. Thanks for the feedback - I'm glad you found it helpful. I've re-tested the updates and am happy to confirm that all tests have passed. #28 is ready to go 🚀

Happy for you to close this issue once the changes have been merged and a new release has been deployed to npm. 

Thanks!

**Comment by tscanlin** [comment] 2020-10-24 06:10
Glad to hear! I merged #28 and the changes are released in `4.5.2`.

Thanks so much for your help identifying and helping me to resolve this issue @ClydeDz, it's very much appreciated!

**Closed** 2020-10-24 06:10 UTC

**Comment by ClydeDz** [comment] 2020-10-24 09:50
Hey @tscanlin, I updated my project to use 4.5.2 but it's producing empty JSON files. Could you please also have a look just in case it's my local env issue only?

**Comment by tscanlin** [comment] 2020-10-24 18:34
Hey, sorry to hear that. Are all JSON files empty? I checked locally and haven't been able to reproduce.

I wonder if it could be caused by the localeCompare change? https://github.com/tscanlin/processmd/pull/28/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R109

Any steps to reproduce this? If you clone this repo and install the dependencies, does `rm -rf ./test/data/output && npm run build:all` work?

**Comment by ClydeDz** [comment] 2020-10-24 22:20
Tim, 

Thanks for the quick reply. I cloned your repository and it did produce the output.json file. I'm not sure if localeCompare could cause this - I had a quick read but it doesn't look like I'm using any locale-specific files. 

However, when I try it from my project that uses 4.5.2 of processmd, it produces empty JSON files. [Here's my project](https://github.com/clydedsouza/clydedsouza-web-api/tree/content-updates) that I've been working on. If you run the PS script `.\Run-Portfolio-API.ps1`, that should run a bunch of tasks and produce JSON files in the root folder itself.  

I tried deleting the node_modules folder, moved from devDependencies to dependencies in the package.json file, and also tried the command `.\node_modules\.bin\processmd --version` to confirm that I've got version 4.5.2.

Thanks!

**Comment by tscanlin** [comment] 2020-10-25 18:15
Let me look into this some more. Also, are you using windows or a Unix based os?

**Comment by tscanlin** [comment] 2020-10-25 18:51
After I realized that was a power shell script I figured you were on windows. I tried one more thing that should hopefully fix this. Can you test out the latest version (`4.5.3`) when you get a chance and let me know if it's still not working?

I realized line endings across unix / windows can sometimes be very problematic.. this is the command I've used to fix this in the past: https://github.com/tscanlin/processmd/blob/master/package.json#L17

**Comment by ClydeDz** [comment] 2020-10-25 21:40
Tim,

Thanks for looking into this. Yes, I'm using Windows. 

Updated to 4.5.3 now but unfortunately, still no luck.
![image](https://user-images.githubusercontent.com/13506613/97119152-2b4bd500-1773-11eb-89f1-32a25805d372.png)

To rule out anything PowerShell, I tried running the command (example below) directly in the VS Code terminal as well, but that didn't work either. 
`.\node_modules\.bin\processmd "inputFolder/**/*.{md}" --stdout --outputDir outputFolder > output.json`

It was working in version 4.5.0 but not after that.  

Thanks!

**Comment by tscanlin** [comment] 2020-10-25 23:17
Hmm, but it works if you run clone and run my project locally? Could you try and clean install after deleting node_modules?

**Comment by ClydeDz** [comment] 2020-10-25 23:43
Yes, weirdly enough, when I clone your project and run locally, it works fine. I also install processmd on your project to test my command line format with your test data, and it works fine. However, when I download a fresh copy of my API project from the latest master, update processmd to 4.5.3, install and run the command, it produces an empty JSON file. I did try deleting node_modules folder multiple times as well.

**Comment by ClydeDz** [comment] 2020-10-26 05:51
Tim,

I think I finally managed to reproduce this issue in your project. If you replace ` .{yml,md}` with ` .{md}` in your commands, it should produce an empty JSON file, I have it set to ` .{md}` because I don't have any YAML files. Do you know why this filter would suddenly break? 

In summary, this works - 
`.\node_modules\.bin\processmd "inputFolder/**/*.{yml,md}" --stdout --outputDir outputFolder > output.json`

but this doesn't - 
`.\node_modules\.bin\processmd "inputFolder/**/*.{md}" --stdout --outputDir outputFolder > output.json`

**Comment by tscanlin** [comment] 2020-10-26 05:57
Great, glad you figured that out! Essentially the reason its not working is because of [bracket expansion](https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html), it doesn't seem to work with a single item, also its completely unnecessary in that case so you can just omit the brackets.
`.\node_modules\.bin\processmd "inputFolder/**/*.md" --stdout --outputDir outputFolder > output.json`

**Comment by ClydeDz** [comment] 2020-10-26 06:03
Perfect, thanks!
